// app/page.tsx
"use client";
// บนสุดของไฟล์
import DownloadBtn from "../components/DownloadBtn";
import { useState, useCallback, useEffect, useRef } from "react";
import ReactFlow, {
  Background,
  Controls,
  applyEdgeChanges,
  applyNodeChanges,
  Node,
  Edge,
  NodeChange,
  EdgeChange,
  ConnectionLineType,
  MarkerType,
  Position,
} from "reactflow";
import "reactflow/dist/style.css";
import dagre from "dagre"; // ใช้จัดเรียง
import { parseSQL } from "../utils/sqlParser";


// SQL เริ่มต้น
const initialSql = `
CREATE TABLE public.users (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  email text UNIQUE NOT NULL,
  created_at timestamp
);

CREATE TABLE public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  user_id uuid REFERENCES public.users(id)
);
`;

// ฟังก์ชันจัด Layout อัตโนมัติ
const getLayoutedElements = (nodes: Node[], edges: Edge[]) => {
  const dagreGraph = new dagre.graphlib.Graph();
  dagreGraph.setDefaultEdgeLabel(() => ({}));

  // ตั้งค่าทิศทาง: 'LR' = ซ้ายไปขวา (Left to Right), 'TB' = บนลงล่าง (Top to Bottom)
  const direction = 'LR'; 
  dagreGraph.setGraph({ rankdir: direction, nodesep: 60, ranksep: 150 });

  nodes.forEach((node) => {
    // คำนวณความสูงคร่าวๆ เพื่อให้จัดเรียงสวย (Header 40px + 30px ต่อแถว)
    // (ดึงจำนวน column มาจาก prop ชั่วคราวที่เราแอบแปะไว้ใน data)
    const colCount = (node.data as any).columnCount || 5;
    dagreGraph.setNode(node.id, { width: 220, height: 40 + (colCount * 30) });
  });

  edges.forEach((edge) => {
    dagreGraph.setEdge(edge.source, edge.target);
  });

  dagre.layout(dagreGraph);

  const layoutedNodes = nodes.map((node) => {
    const nodeWithPosition = dagreGraph.node(node.id);
    return {
      ...node,
      targetPosition: direction === 'LR' ? Position.Left : Position.Top,
      sourcePosition: direction === 'LR' ? Position.Right : Position.Bottom,
      position: {
        x: nodeWithPosition.x - 110, // ปรับ Center
        y: nodeWithPosition.y - (nodeWithPosition.height / 2),
      },
    };
  });

  return { nodes: layoutedNodes, edges };
};

export default function Home() {
  const [sqlInput, setSqlInput] = useState(initialSql);
  const [nodes, setNodes] = useState<Node[]>([]);
  const [edges, setEdges] = useState<Edge[]>([]);

  // --- Logic ย่อขยาย Sidebar ---
  const [sidebarWidth, setSidebarWidth] = useState(400);
  const [isResizing, setIsResizing] = useState(false);
  const sidebarRef = useRef<HTMLDivElement>(null);

  const startResizing = useCallback(() => setIsResizing(true), []);
  const stopResizing = useCallback(() => setIsResizing(false), []);
  const resize = useCallback((mouseMoveEvent: MouseEvent) => {
    if (isResizing) {
      setSidebarWidth(Math.max(200, Math.min(800, mouseMoveEvent.clientX)));
    }
  }, [isResizing]);

  useEffect(() => {
    window.addEventListener("mousemove", resize);
    window.addEventListener("mouseup", stopResizing);
    return () => window.removeEventListener("mousemove", resize);
  }, [resize, stopResizing]);
  // ---------------------------

  const onNodesChange = useCallback(
    (changes: NodeChange[]) => setNodes((nds) => applyNodeChanges(changes, nds)),
    []
  );
  const onEdgesChange = useCallback(
    (changes: EdgeChange[]) => setEdges((eds) => applyEdgeChanges(changes, eds)),
    []
  );

  const handleGenerate = () => {
    const { tables, edges: rels } = parseSQL(sqlInput);

    // 1. สร้าง Node แบบ UI เดิมที่คุณชอบ (HTML ใน Label)
    const initialNodes: Node[] = tables.map((t) => ({
      id: t.id,
      type: 'default', // ใช้ Node มาตรฐาน ไม่ต้องมี Custom Component
      data: { 
        columnCount: t.columns.length, // ส่งไปช่วยคำนวณ Layout
        label: (
          // UI ส่วนนี้คือที่คุณชอบ
          <div className="border border-gray-300 rounded-md shadow-sm bg-white min-w-[200px] overflow-hidden">
            {/* Header */}
            <div className="bg-gray-100 p-2 font-bold text-center border-b border-gray-200 text-gray-700">
              {t.id}
            </div>
            {/* Body */}
            <div className="p-2 text-sm text-gray-600 bg-white">
              {t.columns.map((c) => (
                <div key={c.name} className="flex justify-between py-1 border-b border-gray-50 last:border-0">
                  <span className={`flex items-center gap-1 ${c.isPk ? "text-blue-600 font-semibold" : ""}`}>
                    {c.isPk && "🔑"} {c.name}
                  </span>
                  <span className="text-gray-400 text-xs ml-2 font-mono">{c.type}</span>
                </div>
              ))}
            </div>
          </div>
        )
      },
      position: { x: 0, y: 0 } // เดี๋ยว Dagre จัดให้
    }));

    // 2. สร้างเส้นเชื่อม (Edges)
    const initialEdges: Edge[] = rels.map((r, i) => ({
      id: `e-${i}`,
      source: r.source,
      target: r.target,
      animated: true,
      type: 'smoothstep', // เส้นหักมุมสวยๆ
      style: { stroke: '#64748b', strokeWidth: 1.5 },
      markerEnd: {
        type: MarkerType.ArrowClosed,
        color: '#64748b',
      },
    }));

    // 3. จัดระเบียบด้วย Dagre
    const layouted = getLayoutedElements(initialNodes, initialEdges);

    setNodes(layouted.nodes);
    setEdges(layouted.edges);
  };

  return (
    <main className={`flex h-screen w-screen bg-gray-50 overflow-hidden ${isResizing ? 'cursor-col-resize select-none' : ''}`}>
      
      {/* Sidebar */}
      <div 
        ref={sidebarRef}
        style={{ width: sidebarWidth }}
        className="flex flex-col border-r bg-white shadow-lg z-10 flex-shrink-0"
      >
        <div className="p-4 border-b flex justify-between items-center bg-gray-50">
           <h1 className="font-bold text-gray-700">SQL Diagram</h1>
           <button 
             onClick={handleGenerate} 
             className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-1.5 rounded-md text-sm font-medium transition-colors shadow-sm"
           >
             Generate
           </button>
        </div>
        
        <div className="flex-1 relative">
          <textarea
            className="w-full h-full p-4 font-mono text-xs md:text-sm bg-[#1e1e1e] text-green-400 resize-none focus:outline-none leading-relaxed"
            value={sqlInput}
            onChange={(e) => setSqlInput(e.target.value)}
            spellCheck={false}
            placeholder="Paste CREATE TABLE statements..."
          />
        </div>
      </div>

      {/* Resizer */}
      <div
        onMouseDown={startResizing}
        className="w-1.5 h-full bg-gray-200 hover:bg-blue-400 cursor-col-resize transition-colors z-20"
      />

      {/* Diagram Canvas */}
      <div className="flex-1 h-full bg-gray-50 relative">
        <ReactFlow
          nodes={nodes}
          edges={edges}
          onNodesChange={onNodesChange}
          onEdgesChange={onEdgesChange}
          connectionLineType={ConnectionLineType.SmoothStep}
          fitView
        >
          <Background color="#cbd5e1" gap={20} size={1} />
          <Controls className="bg-white shadow-md border border-gray-200 rounded-lg" />
          <DownloadBtn /> 

        </ReactFlow>
      </div>
    </main>
  );
}